name: StruRW
gnn: GS
num_layers: 3
hid_dim: 128
dropout_ratio: 0.4
cls_layers: 2
cls_dim: 128
activation: relu
num_neigh: -1
batch_size: 0
optimizer: Adam
lr: 0.001
weight_decay: 0.0001
mmd: true
mmd_weight: 0.1
pooling: mean
reweight: true
pseudo: true
ew_start: 100
ew_freq: 20
lamb: 0.6
mode: erm
bn: false
epochs: 200
tuned_params:
- epochs
- hid_dim
- lr
- weight_decay
