name: SpecReg
gnn: gcn
num_layers: 2
hid_dim: 256
dropout_ratio: 0.1
activation: relu
mode: node
num_neigh: -1
batch_size: 0
optimizer: Adam
weight_decay: 0.005
lr: 0.0005
ppmi: true
adv_dim: 40
reg_mode: true
gamma_adv: 0.1
thr_smooth: -1
gamma_smooth: 0.001
thr_mfr: -1
gamma_mfr: 0.001
epochs: 400
tuned_params:
- dropout_ratio
- epochs
- hid_dim
- lr
- num_layers
- weight_decay
