name: SimGDA
gnn: gcn
num_layers: 4
hid_dim: 64
dropout_ratio: 0.1
filename:  gnn_test.txt
activation: relu
mode: node
s_pnums: 0
t_pnums: 30
num_neigh: -1
batch_size: 0
optimizer: Adam
lr: 0.01
weight_decay: 0.001
scheduler: StepLR
step_size: 10
gamma: 0.1
mmd: true
mmd_weight: 0.1
adv: false
adv_weight: 0.1
