name: DGSDA
gnn: gcn
num_layers: 2
hid_dim: 64
dropout_ratio: 0.3
dprate: 0.3
activation: relu
mode: node
num_neigh: -1
batch_size: 0
optimizer: Adam
lr: 0.0005
weight_decay: 0.01
K: 5
cls_weight: 1.0
alpha: 0.05
beta: 0.1
gamma: 0.01
delta: 0.1
probe_samples: 2048
feature_mmd_samples: 256
feature_mmd_times: 2
probe_mmd_samples: 256
probe_mmd_times: 2
probe_mmd_dim: 64
epochs: 400
dp_ratio: 0.3
tuned_params:
- epochs
- hid_dim
- lr
- weight_decay
