model:
  K: [5, 8, 10, 20]
  alpha: [0.05]
  beta: [0.1]
  domain_weight: [0.1]
  dp_ratio: [0.3]
  dropout_ratio: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  epochs: [100, 200, 300, 400, 500, 800, 1000]
  gamma: [0.01]
  gamma_adv: [0.1]
  gamma_mfr: [0.001]
  gamma_smooth: [0.001]
  hid_dim: [64, 128]
  k_cross: [20]
  k_within: [10]
  lamb: [0.6, 0.8]
  lr: [0.0001, 0.0003, 0.001, 0.003, 0.005, 0.01]
  ls_lambda: [3.0, 5.0]
  lw_lambda: [0.01]
  num_layers: [1, 2, 3, 4, 5]
  pool_ratio: [0.2]
  rw_lmda: [1]
  s_pnums: [0]
  t_pnums: [5, 10]
  weight: [0.002, 0.005, 0.01, 0.02, 5, 10]
  weight_decay: [0.0, 0.0005, 0.001, 0.003, 0.005, 0.01]
