name: UDAGCN
gnn: gcn
num_layers: 2
hid_dim: 128
dropout_ratio: 0.4
activation: relu
mode: node
num_neigh: -1
batch_size: 0
optimizer: Adam
lr: 0.0005
weight_decay: 0.001
epochs: 400
use_mask: true
tuned_params:
- epochs
- hid_dim
- lr
- weight_decay
