name: "Airport"

root: "/home/irteam/data-vol1/data/Airport"
domains: ["BRAZIL", "EUROPE", "USA"]

raw_file_names: ["edgelist.txt", "labels.txt"]
processed_file_names: ["data.pt"]

train_split: 0.8
val_split: 0.2
test_split: 0.0 # actually unused

metric: "micro_f1"



