name: "MAG"

root: "/data/biniyam/datasets/pygda_data/data/MAG"
domains: ["MAG_CN", "MAG_DE", "MAG_FR", "MAG_RU", "MAG_JP", "MAG_US"]

raw_file_names: ["labels_20.pt"]
processed_file_names: ["data.pt"]

train_split: 0.8
val_split: 0.2
test_split: 0.0 # actually unused

metric: "macro_f1"