# MAG — GDABench baselines only
model:
  lr: [0.0001, 0.001, 0.003]
  weight_decay: [0.0001, 0.001, 0.003]
  num_layers: [2]
  dropout_ratio: [0.1, 0.2, 0.3, 0.4, 0.5]
  hid_dim: 300
  epochs: [200, 400, 600, 800]
