name: FDA
gnn: gcn
num_layers: 2
hid_dim: 64
dropout_ratio: 0.1
activation: relu
mode: node
num_neigh: -1
batch_size: 0
optimizer: Adam
lr: 0.005
weight_decay: 0.01
epochs: 300
filter: mono
K: 15
mmd_weight: 0.0
probe_mmd_weight: 0.5
probe_sem_weight: 0.5
probe_sem_class_conditional: false
feature_align_proj: true
feature_align_activation: relu
mmd_sampling_num: 1000
mmd_times: 3
nonnegative_filter_params: false
tuned_params:
- K
- dropout_ratio
- epochs
- filter
- lr
- mmd_sampling_num
- mmd_times
- mmd_weight
- nonnegative_filter_params
- probe_mmd_weight
- probe_sem_class_conditional
- probe_sem_weight
- weight_decay
